// Single source of truth for the portfolio data model.
//
// Two file shapes live here. `photos.json` is machine-generated by
// scripts/photos/{manifest,categorize}.ts and lists every photo on R2 plus
// AI-derived category suggestions. `portfolio.json` is hand-edited (via the
// /builder UI) and decides which photos display, in what order, with what
// category memberships, and at what size/format.
//
// Loaders, scripts, and the save endpoint all consume these schemas. TS types
// flow from `z.infer<>` so changes here propagate everywhere.

import { z } from "zod";

// ─── photos.json ───────────────────────────────────────────────────────────

export const PhotoSchema = z.object({
  /** Basename without extension. e.g. "IMG_5007" or "merged (2)". */
  id: z.string().min(1),
  /** R2 source filename, with extension. e.g. "IMG_5007.jpg". */
  filename: z.string().min(1),
  /** Orientation-corrected dimensions (long edge of source). */
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  /** Categories Gemini picked from the controlled vocab. */
  ai_categories: z.array(z.string()).default([]),
  /** Categories Gemini suggested outside the vocab — for vocab discovery. */
  ai_suggested_categories: z.array(z.string()).default([]),
});

export const PhotosFileSchema = z.object({
  version: z.literal(1),
  photos: z.array(PhotoSchema),
});

export type Photo = z.infer<typeof PhotoSchema>;
export type PhotosFile = z.infer<typeof PhotosFileSchema>;

// ─── portfolio.json ────────────────────────────────────────────────────────

export const CategorySchema = z.object({
  /** URL-safe slug. Used as the chip filter id. */
  id: z.string().min(1),
  /** Display label shown in chips. */
  label: z.string().min(1),
});

export const SizeSchema = z.enum(["270", "540", "1k", "full"]);
export const FormatSchema = z.enum(["sdr_webp", "hdr_jpg"]);

/** Render settings drive both the live site and the builder's preview. */
export const RenderSchema = z.object({
  tile_size: SizeSchema.default("540"),
  tile_format: FormatSchema.default("sdr_webp"),
  lightbox_size: SizeSchema.default("1k"),
  lightbox_format: FormatSchema.default("hdr_jpg"),
});

export const PortfolioSchema = z.object({
  version: z.literal(1),
  categories: z.array(CategorySchema),
  /** Photos displayed by the live site, in order. ALLOWLIST: photos in
   *  photos.json but not in `order` are on R2 but not in the portfolio.
   *  This is the "All" view's order — categories without their own entry
   *  in `category_orders` fall back to filtering this. */
  order: z.array(z.string()),
  /** Per-photo category memberships. Keys are photo ids; values are
   *  category ids that must exist in `categories`. */
  photo_categories: z.record(z.string(), z.array(z.string())),
  /** Per-category photo ordering. Keys are category ids; values are the
   *  photo ids displayed under that category, in display order. Sparse —
   *  a missing entry means "use global `order` filtered to this category".
   *  Maintained automatically when photos toggle in/out of categories. */
  category_orders: z.record(z.string(), z.array(z.string())).default({}),
  render: RenderSchema.default({
    tile_size: "540",
    tile_format: "sdr_webp",
    lightbox_size: "1k",
    lightbox_format: "hdr_jpg",
  }),
});

export type Category = z.infer<typeof CategorySchema>;
export type Size = z.infer<typeof SizeSchema>;
export type Format = z.infer<typeof FormatSchema>;
export type Render = z.infer<typeof RenderSchema>;
export type Portfolio = z.infer<typeof PortfolioSchema>;
